version: 1
disable_existing_loggers: false

# How your log messages will be formatted
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(module)s - %(lineno)d - %(levelname)s - %(message)s'

# Where the log messages will go (e.g., console, file)
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: app.log
    maxBytes: 10485760 # 10 MB
    backupCount: 5
    encoding: utf8

# The "root" logger catches all logs from any module
root:
  level: DEBUG
  handlers: [console, file]