chunking:
  chunk_size: 500
  chunk_overlap: 50
embedding:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"  # "text-embedding-3-small-custom"
  embedding_dimension : 384
azure: 
  container_name: "ai-files"
files:
  csv_blob_name : "data.csv"
  faiss_index_blob_name : "index.faiss"
  datastore_blob_name : "index.pkl"

